### ISSUE TITLE
Start application (jar)?

### ISSUE THREAD

**Issue by pAs2aL** [Ekito/spring-boot-gwt#3]
How can i start the application? I want to use spring boot with the provided tomcat and include gwt. 
I want to start my application as a jar-file (java -jar). Is it possible and can you describe the process?

**Comment by pAs2aL** [comment]
or start it from the war (embedded tomcat)

**Comment by arnaudgiuliani** [comment]
Hello,

you can't directly launch gwt with a java -jar command, because you have to launch the gwt engine. You have two options for that (maven command line): 
- mvn gwt:run (or mvn gwt:debug) to launch the app in a embedded jetty server
- mvn package to package a war archive, that you can drop to your tomcat server

I Think the first option can help you launch the app in standalone mode.

Regards.

**Comment by pAs2aL** [comment]
Hi, thanks for your answer. But if you are using spring boot, you don't want to create a war and deploy it to a tomcat. The great thing about spring boot is, that it provides already a tomcat. I can start the application and the tomcat using the jar. Or how do you want to start your application? If you want to generate a war file and put it into a tomcat, than you don't have to use spring boot. I also posted on stackoverflow. There i describe, what i want to achieve.
http://stackoverflow.com/questions/27882165/build-sprint-boot-application-with-gwt

Regards

**Comment by arnaudgiuliani** [comment]
Hi,

I understand, but bare in mind that GWT need to be compiled (java to javascript). That's why I make this app as a web archive, in order to keep it compatible with GWT setup. You can still launch it as "dev" mode, but for production, you should use the war. The idea of having Spring boot, is that you can launch your server part as is and work on it.
(use these maven commands : mvn gwt:run or mvn spring-boot:run)

Then If you want to make this gwt app a standalone jar, you can look at few things : 
- rework this pom.xml as a jar archetype
- configure maven gwt plugin to handle compilation files to be in right folders
- make sure standalone execution take in account the servlet files (web-inf folder)

You can fork this project and look at the solution. Feel free to make a pull request ;)

Regards.

**Comment by pAs2aL** [comment]
Ok, thanks for your answer :-)
